import { FormField } from "@/hooks/types";

export const HomeFormType: FormField[] = [
  {
    name: "_id",
    type: "text",
    required: true,
    label: "ID",
    placeholder: "Enter ID",
  },
  {
    name: "title",
    type: "text",
    required: true,
    label: "Title",
    placeholder: "Enter title",
  },
  {
    name: "subTitle",
    type: "text",
    required: true,
    label: "Subtitle",
    placeholder: "Enter subtitle",
  },
  {
    name: "description",
    type: "textarea",
    required: true,
    label: "Description",
    placeholder: "Enter description",
  },
  {
    name: "section1._id",
    type: "text",
    required: true,
    label: "Section 1 ID",
    placeholder: "Enter section 1 ID",
  },
  {
    name: "section1.title",
    type: "text",
    required: true,
    label: "Section 1 Title",
    placeholder: "Enter section 1 title",
  },
  {
    name: "section1.subtitle",
    type: "text",
    required: true,
    label: "Section 1 Subtitle",
    placeholder: "Enter section 1 subtitle",
  },
  {
    name: "section1.description",
    type: "textarea",
    required: true,
    label: "Section 1 Description",
    placeholder: "Enter section 1 description",
  },
  {
    name: "section2._id",
    type: "text",
    required: true,
    label: "Section 2 ID",
    placeholder: "Enter section 2 ID",
  },
  {
    name: "section2.title",
    type: "text",
    required: true,
    label: "Section 2 Title",
    placeholder: "Enter section 2 title",
  },
  {
    name: "section2.subtitle",
    type: "text",
    required: true,
    label: "Section 2 Subtitle",
    placeholder: "Enter section 2 subtitle",
  },
  {
    name: "section2.description",
    type: "textarea",
    required: true,
    label: "Section 2 Description",
    placeholder: "Enter section 2 description",
  },
  {
    name: "section2.subContents[0]._id",
    type: "text",
    required: false,
    label: "Section 2 SubContent ID",
    placeholder: "Enter subcontent ID",
  },
  {
    name: "section2.subContents[0].title",
    type: "text",
    required: false,
    label: "Section 2 SubContent Title",
    placeholder: "Enter subcontent title",
  },
  {
    name: "section2.subContents[0].description",
    type: "textarea",
    required: false,
    label: "Section 2 SubContent Description",
    placeholder: "Enter subcontent description",
  },
  {
    name: "videoUrl",
    type: "text",
    required: false,
    label: "Video URL",
    placeholder: "Enter video URL",
  },
];
